# Air config file
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["vendor", "tmp", "migrate"]
  delay = 1000 # ms
  poll = true           # ADD THIS
  poll_interval = 500   # ADD THIS (check every 500ms)

[log]
  time = true